### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by l3str4nge** [keonlee9420/STYLER#3]
Hi, I noticed some undefined names around the code:

`synthesize.py:495:67: F821 undefined name 'reference'`
`noise_mixer_refs.py:56:42: F821 undefined name 'eps'`
`noise_mixer_refs.py:59:40: F821 undefined name 'eps'`

**Comment by keonlee9420** [comment]
Hi @mateuszz0000, thanks for the reports. I just corrected the first issue (see the commit log). The other issues were missed since they are not used in the current implementation. I temporally allocate `1e-6` to each of 'eps', but it is meaningless for now.

**Comment by l3str4nge** [comment]
Great :)
