### ISSUE TITLE
Low resource languages that won't work with MFA?

### ISSUE THREAD

**Issue by michael-conrad** [keonlee9420/STYLER#4]
Is there a way to fine tune a model or training two languages side by side such that a very low resource language can be trained with the voices of a high resource language?

**Comment by keonlee9420** [comment]
Hi @michael-conrad, please refer to [this](https://github.com/keonlee9420/Emotional-FastSpeech2) for preparing MFA on your own dataset. Unfortunately, I'm not sure about adapting low resource language without using MFA under the current model configuration, but thinking of [voice conversion](https://paperswithcode.com/task/voice-conversion#:~:text=Voice%20Conversion%20is%20a%20technology,without%20changing%20the%20linguistic%20information.) (VC) domain for the data efficient training and voice factor transfer. I hope it helps.

**Comment by keonlee9420** [comment]
You may also get some insights from 3.4 Low-resource acoustic model section of [this review paper](https://arxiv.org/abs/2104.09995).

**Comment by keonlee9420** [comment]
You may also get some insights from `3.4 Low-resource acoustic model` section of [this review paper](https://arxiv.org/abs/2104.09995).

**Comment by michael-conrad** [comment]
As I'm not a researcher, but instead someone trying to leverage TTS tech to create lesson materials for an endangered language, most of this is beyond my ability time wise to try and leverage.

Thanks for your pointers though.
